### ISSUE TITLE
ERROR  登陆Nike官网失败[401]!

### ISSUE THREAD

**Issue by FaiChou** [cxiaoer/NikeRobot#1]
> 2016-12-02 11:02:13,628  MainThread  INFO  开始登陆Nike官网了.......
2016-12-02 11:02:13,673  MainThread  INFO  Starting new HTTP connection (1): www.nike.com
2016-12-02 11:02:14,758  MainThread  INFO  Starting new HTTPS connection (1): unite.nike.com
2016-12-02 11:02:56,950  MainThread  ERROR  登陆Nike官网失败[401]!

**Comment by cool403** [comment]
`nike` 首页登陆`url`发生变化了; 新的登陆地址为：
```
https://www.nike.com/profile/login?Content-Locale=zh_CN
```

**Comment by FaiChou** [comment]
你好，感谢回复。
  刚才用chrome登陆，在DeveloperTools 上发现登陆地址没有变化呀。
`Request URL:https://unite.nike.com/loginWithSetCookie?appVersion=211&experienceVersion=179&uxid=com.nike.commerce.nikedotcom.web&locale=zh_CN&backendEnvironment=default&browser=Google%20Inc.&os=undefined&mobile=false&native=false`

请问你是如何获取的呢？
我用PostMan试了好多地址，post请求了无数遍，总是失败，这是什么原因呢？请赐教

**Comment by cool403** [comment]
我从下面的地址进去的:
```js
https://secure-store.nike.com/cn/checkout/html/cart.jsp?country=CN&country=CN&DPSLogout=true&_requestid=17261188
```
在这里点击登录，就会发现新的登录地址了
