### ISSUE TITLE
我运行不起来，提示没有redis

### ISSUE THREAD

**Issue by star-andy** [cxiaoer/NikeRobot#2]
方便留个联系方式交流下吗?  我也是aj粉  可是总是买不到鞋

**Comment by star-andy** [comment]
已经运行起来了  但是我输入一个网址无法自动添加购物车

**Comment by FaiChou** [comment]
是这个错误吗？
`AttributeError: 'NoneType' object has no attribute '__dict__'`

**Comment by cool403** [comment]
@FaiChou 估计是某个连接正则没提取到内容

**Comment by cool403** [comment]
@qinyang1018 我自己本地试了一下，貌似可以诶，方便给一下哪个网址么

**Comment by star-andy** [comment]
我就是随便找的链接，然后我改了下你上面的尺码

**Comment by star-andy** [comment]
如果方便加下QQ   8400074探讨下

**Comment by FaiChou** [comment]
http://store.nike.com/cn/zh_cn/pd/zm-pegasus-33-shield-%E5%A4%A7%E7%AB%A5%E8%B7%91%E6%AD%A5%E7%AB%A5%E9%9E%8B/pid-11157895/pgid-11674613

这个失败地址

**Comment by star-andy** [comment]
我还没遇见能成功的

**Comment by cool403** [comment]
@qinyang1018 @FaiChou 现在应该好了；
